GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDk0NzE2NTksImV4cCI6MTY0OTQ3MTY4OSwiYXVkIjoiNjI0Yzc0NTU0YmMwNmM3OWYxYjgxODA0IiwiaXNzIjoiY2F0dGhhbmggZGVwIHRyYWkgdm8gZG9pIn0.MZ4dpK0ZH355NfhDPM-yzFtr2ZQ9OTdukSHkV2j8ArQ

### Login route
POST  http://localhost:3000/auth/login/
Content-Type: application/json

{
    "username": "testuser",
    "password": "testuser"
}

### Register route
POST http://localhost:3000/auth/register/
Content-Type: application/json

{
    "username": "tesdsssst",
    "password": "fst",
    "name": "tesdsssst"
}

### Refresh token route
POST http://localhost:3000/auth/refresh-token/
Content-Type: application/json

{
    "refreshtoken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTEzMDcyNjEsImV4cCI6MTY1Mzg5OTI2MSwiYXVkIjoiMjA3NyIsImlzcyI6ImNhdHRoYW5oIGRlcCB0cmFpIHZvIGRvaSIsImp0aSI6ImI1Zjc5NmJlLTRiMDgtNGM4OC1iYWE1LTIwNmZjY2JiMTY2MiJ9.eLnI8xfnqvV8W6VRm4gd8udF2tJzZ3aYCOsQFmGQBkA"
}

### Logout route
DELETE http://localhost:3000/auth/logout/
Content-Type: application/json

{
    "refreshtoken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTAzNzQ4NTYsImV4cCI6MTY1Mjk2Njg1NiwiYXVkIjoiMSIsImlzcyI6ImNhdHRoYW5oIGRlcCB0cmFpIHZvIGRvaSIsImp0aSI6ImZhN2VlZmQ2LWQwZjMtNDMzZi04MzkzLWY1YjRjZTAwNzc0NCJ9.W0Fy3z-NY46ISJMAKQBTebN_0_z5Hwn-gkDuHu1luoQ"
}

